import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongoose';
import { Product } from '@/lib/models/Schema';

export async function GET() {
  try {
    await dbConnect();
    
    // Clear existing featured products for a clean slate
    await Product.deleteMany({});

    const seedData = [
      {
            "name": "Apple iPhone 5s",
            "sku": "APPLE-IPHONE-5S-0",
            "category": "Smartphones & Tablets",
            "retailPrice": 3360,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 5s",
            "threeDModelUrl": "/assets/models/apple-iphone-5s.glb"
      },
      {
            "name": "Apple iPhone XS",
            "sku": "APPLE-IPHONE-XS-1",
            "category": "Smartphones & Tablets",
            "retailPrice": 18600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone XS",
            "threeDModelUrl": "/assets/models/apple-iphone-xs.glb"
      },
      {
            "name": "Apple iPhone 12 Pro",
            "sku": "APPLE-IPHONE-12-2",
            "category": "Smartphones & Tablets",
            "retailPrice": 43200,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 12 Pro",
            "threeDModelUrl": "/assets/models/apple-iphone-12-pro.glb"
      },
      {
            "name": "Apple iPhone 13 Pro Max",
            "sku": "APPLE-IPHONE-13-3",
            "category": "Smartphones & Tablets",
            "retailPrice": 63600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 13 Pro Max",
            "threeDModelUrl": "/assets/models/apple-iphone-13-pro-max.glb"
      },
      {
            "name": "Apple iPhone 13 Pro Max (256GB Variant)",
            "sku": "APPLE-IPHONE-13-4",
            "category": "Smartphones & Tablets",
            "retailPrice": 68400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 13 Pro Max (256GB Variant)",
            "threeDModelUrl": "/assets/models/apple-iphone-13-pro-max-variant.glb"
      },
      {
            "name": "Apple iPhone 14 Pro",
            "sku": "APPLE-IPHONE-14-5",
            "category": "Smartphones & Tablets",
            "retailPrice": 74400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 14 Pro",
            "threeDModelUrl": "/assets/models/apple-iphone-14-pro.glb"
      },
      {
            "name": "Apple iPhone 14 Pro Max",
            "sku": "APPLE-IPHONE-14-6",
            "category": "Smartphones & Tablets",
            "retailPrice": 81600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 14 Pro Max",
            "threeDModelUrl": "/assets/models/apple-iphone-14-pro-max.glb"
      },
      {
            "name": "Apple iPhone 15 Pro Max",
            "sku": "APPLE-IPHONE-15-7",
            "category": "Smartphones & Tablets",
            "retailPrice": 102000,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Apple iPhone 15 Pro Max",
            "threeDModelUrl": "/assets/models/apple-iphone-15-pro-max.glb"
      },
      {
            "name": "Apple iPhone 16",
            "sku": "APPLE-IPHONE-16-8",
            "category": "Smartphones & Tablets",
            "retailPrice": 94800,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 16",
            "threeDModelUrl": "/assets/models/apple-iphone-16.glb"
      },
      {
            "name": "Apple iPhone 16 Pro Max",
            "sku": "APPLE-IPHONE-16-9",
            "category": "Smartphones & Tablets",
            "retailPrice": 126000,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Apple iPhone 16 Pro Max",
            "threeDModelUrl": "/assets/models/apple-iphone-16-pro-max.glb"
      },
      {
            "name": "Apple iPhone 15",
            "sku": "APPLE-IPHONE-17-10",
            "category": "Smartphones & Tablets",
            "retailPrice": 78000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 15",
            "threeDModelUrl": "/assets/models/apple-iphone-17-6-3-inch.glb"
      },
      {
            "name": "Apple iPhone 15 Plus",
            "sku": "APPLE-IPHONE-17-11",
            "category": "Smartphones & Tablets",
            "retailPrice": 88000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 15 Plus",
            "threeDModelUrl": "/assets/models/apple-iphone-17-air-concept.glb"
      },
      {
            "name": "Apple iPhone 15 Pro",
            "sku": "APPLE-IPHONE-17-12",
            "category": "Smartphones & Tablets",
            "retailPrice": 98000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 15 Pro",
            "threeDModelUrl": "/assets/models/apple-iphone-17-pro-concept.glb"
      },
      {
            "name": "Apple iPhone 14",
            "sku": "APPLE-IPHONE-17-13",
            "category": "Smartphones & Tablets",
            "retailPrice": 66000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 14",
            "threeDModelUrl": "/assets/models/apple-iphone-17-pro-concept-variant.glb"
      },
      {
            "name": "Apple iPhone 14 Plus",
            "sku": "APPLE-IPHONE-17-14",
            "category": "Smartphones & Tablets",
            "retailPrice": 74000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 14 Plus",
            "threeDModelUrl": "/assets/models/apple-iphone-17-pro-6-3-inch.glb"
      },
      {
            "name": "Apple iPhone 13",
            "sku": "APPLE-IPHONE-17-15",
            "category": "Smartphones & Tablets",
            "retailPrice": 55000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 13",
            "threeDModelUrl": "/assets/models/apple-iphone-17-pro-6-3-inch-variant.glb"
      },
      {
            "name": "Apple iPhone 13 Pro",
            "sku": "APPLE-IPHONE-17-16",
            "category": "Smartphones & Tablets",
            "retailPrice": 68000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 13 Pro",
            "threeDModelUrl": "/assets/models/apple-iphone-17-pro-max-concept.glb"
      },
      {
            "name": "Apple iPhone 12",
            "sku": "APPLE-IPHONE-18-17",
            "category": "Smartphones & Tablets",
            "retailPrice": 42000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 12",
            "threeDModelUrl": "/assets/models/apple-iphone-18-pro-max-heritage-edition.glb"
      },
      {
            "name": "Apple iPhone 11",
            "sku": "APPLE-IPHONE-DU-18",
            "category": "Smartphones & Tablets",
            "retailPrice": 32000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 11",
            "threeDModelUrl": "/assets/models/apple-iphone-duo-concept.glb"
      },
      {
            "name": "Apple iPhone 11 Pro Max",
            "sku": "APPLE-IPHONE-DU-19",
            "category": "Smartphones & Tablets",
            "retailPrice": 45000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone 11 Pro Max",
            "threeDModelUrl": "/assets/models/apple-iphone-duo-concept-variant.glb"
      },
      {
            "name": "Apple iPhone SE (3rd Gen)",
            "sku": "APPLE-IPHONE-DU-20",
            "category": "Smartphones & Tablets",
            "retailPrice": 28000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPhone SE (3rd Gen)",
            "threeDModelUrl": "/assets/models/apple-iphone-duo-fold-animated.glb"
      },
      {
            "name": "Apple iPad Pro",
            "sku": "APPLE-IPAD-PRO-21",
            "category": "Smartphones & Tablets",
            "retailPrice": 70800,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple iPad Pro",
            "threeDModelUrl": "/assets/models/apple-ipad-pro.glb"
      },
      {
            "name": "Samsung Galaxy S21 Ultra",
            "sku": "SAMSUNG-GALAXY--22",
            "category": "Smartphones & Tablets",
            "retailPrice": 33600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy S21 Ultra",
            "threeDModelUrl": "/assets/models/samsung-galaxy-s21-ultra.glb"
      },
      {
            "name": "Samsung Galaxy S22 Ultra",
            "sku": "SAMSUNG-GALAXY--23",
            "category": "Smartphones & Tablets",
            "retailPrice": 38400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy S22 Ultra",
            "threeDModelUrl": "/assets/models/samsung-galaxy-s22-ultra.glb"
      },
      {
            "name": "Samsung Galaxy S24 Ultra",
            "sku": "SAMSUNG-GALAXY--24",
            "category": "Smartphones & Tablets",
            "retailPrice": 98400,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Samsung Galaxy S24 Ultra",
            "threeDModelUrl": "/assets/models/samsung-galaxy-s24-ultra.glb"
      },
      {
            "name": "Samsung Galaxy S23 Ultra",
            "sku": "SAMSUNG-GALAXY--25",
            "category": "Smartphones & Tablets",
            "retailPrice": 75000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy S23 Ultra",
            "threeDModelUrl": "/assets/models/samsung-galaxy-s25-ultra-concept.glb"
      },
      {
            "name": "Samsung Galaxy S23+",
            "sku": "SAMSUNG-GALAXY--26",
            "category": "Smartphones & Tablets",
            "retailPrice": 58000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy S23+",
            "threeDModelUrl": "/assets/models/samsung-galaxy-s25-ultra-concept-variant.glb"
      },
      {
            "name": "Samsung Galaxy S23",
            "sku": "SAMSUNG-GALAXY--27",
            "category": "Smartphones & Tablets",
            "retailPrice": 48000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy S23",
            "threeDModelUrl": "/assets/models/samsung-galaxy-s26-ultra-concept.glb"
      },
      {
            "name": "Samsung Galaxy Z Flip 3",
            "sku": "SAMSUNG-GALAXY--28",
            "category": "Smartphones & Tablets",
            "retailPrice": 30000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy Z Flip 3",
            "threeDModelUrl": "/assets/models/samsung-galaxy-z-flip-3.glb"
      },
      {
            "name": "Samsung Galaxy Z Fold 5",
            "sku": "SAMSUNG-GALAXY--29",
            "category": "Smartphones & Tablets",
            "retailPrice": 110000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy Z Fold 5",
            "threeDModelUrl": "/assets/models/samsung-galaxy-z-fold-7-concept.glb"
      },
      {
            "name": "OnePlus 12",
            "sku": "ONEPLUS-135-CON-30",
            "category": "Smartphones & Tablets",
            "retailPrice": 62000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium OnePlus 12",
            "threeDModelUrl": "/assets/models/oneplus-135-concept.glb"
      },
      {
            "name": "Realme 12 5G",
            "sku": "REALME-12-5G-31",
            "category": "Smartphones & Tablets",
            "retailPrice": 17400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Realme 12 5G",
            "threeDModelUrl": "/assets/models/realme-12-5g.glb"
      },
      {
            "name": "Nothing Phone (2a)",
            "sku": "NOTHING-PHONE-4-32",
            "category": "Smartphones & Tablets",
            "retailPrice": 28000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Nothing Phone (2a)",
            "threeDModelUrl": "/assets/models/nothing-phone-4a.glb"
      },
      {
            "name": "Vivo X80 Pro",
            "sku": "VIVO-X80-PRO-33",
            "category": "Smartphones & Tablets",
            "retailPrice": 45600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vivo X80 Pro",
            "threeDModelUrl": "/assets/models/vivo-x80-pro.glb"
      },
      {
            "name": "Vivo X200 Pro",
            "sku": "VIVO-X200-PRO-34",
            "category": "Smartphones & Tablets",
            "retailPrice": 66000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vivo X200 Pro",
            "threeDModelUrl": "/assets/models/vivo-x200-pro.glb"
      },
      {
            "name": "Vivo X100 Pro",
            "sku": "VIVO-X300-ULTRA-35",
            "category": "Smartphones & Tablets",
            "retailPrice": 68000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vivo X100 Pro",
            "threeDModelUrl": "/assets/models/vivo-x300-ultra.glb"
      },
      {
            "name": "Vivo X100 Ultra (Green)",
            "sku": "VIVO-X300-ULTRA-36",
            "category": "Smartphones & Tablets",
            "retailPrice": 82000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vivo X100 Ultra (Green)",
            "threeDModelUrl": "/assets/models/vivo-x300-ultra-green.glb"
      },
      {
            "name": "Apple MacBook Pro 2021 (14/16-inch)",
            "sku": "APPLE-MACBOOK-P-37",
            "category": "Laptops & Computers",
            "retailPrice": 98400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple MacBook Pro 2021 (14/16-inch)",
            "threeDModelUrl": "/assets/models/apple-macbook-pro-2021-14-16-inch.glb"
      },
      {
            "name": "Apple MacBook Pro 16-inch M3 2024",
            "sku": "APPLE-MACBOOK-P-38",
            "category": "Laptops & Computers",
            "retailPrice": 222000,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Apple MacBook Pro 16-inch M3 2024",
            "threeDModelUrl": "/assets/models/apple-macbook-pro-16-inch-m3-2024.glb"
      },
      {
            "name": "Apple MacBook Air M2 13-inch",
            "sku": "APPLE-MACBOOK-P-39",
            "category": "Laptops & Computers",
            "retailPrice": 95000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple MacBook Air M2 13-inch",
            "threeDModelUrl": "/assets/models/apple-macbook-pro-14-inch-m5-concept.glb"
      },
      {
            "name": "HP Pavilion x360 Laptop",
            "sku": "HP-PAVILION-X36-40",
            "category": "Laptops & Computers",
            "retailPrice": 45600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium HP Pavilion x360 Laptop",
            "threeDModelUrl": "/assets/models/hp-pavilion-x360-laptop.glb"
      },
      {
            "name": "Apple AirPods Pro",
            "sku": "APPLE-AIRPODS-P-41",
            "category": "Wearables & Audio",
            "retailPrice": 1440,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Apple AirPods Pro",
            "threeDModelUrl": "/assets/models/apple-airpods-pro.glb"
      },
      {
            "name": "Apple Watch Series 7",
            "sku": "APPLE-WATCH-SER-42",
            "category": "Wearables & Audio",
            "retailPrice": 21600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Apple Watch Series 7",
            "threeDModelUrl": "/assets/models/apple-watch-series-7.glb"
      },
      {
            "name": "Apple Watch Ultra 2",
            "sku": "APPLE-WATCH-ULT-43",
            "category": "Wearables & Audio",
            "retailPrice": 54000,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Apple Watch Ultra 2",
            "threeDModelUrl": "/assets/models/apple-watch-ultra-2.glb"
      },
      {
            "name": "Samsung Galaxy Watch 7",
            "sku": "SAMSUNG-GALAXY--44",
            "category": "Wearables & Audio",
            "retailPrice": 25200,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Samsung Galaxy Watch 7",
            "threeDModelUrl": "/assets/models/samsung-galaxy-watch-7.glb"
      },
      {
            "name": "Amazon Echo Dot 3rd Gen",
            "sku": "JBL-CHARGE-3-PO-45",
            "category": "Wearables & Audio",
            "retailPrice": 1020,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Amazon Echo Dot 3rd Gen",
            "threeDModelUrl": "/assets/models/jbl-charge-3-portable-speaker.glb"
      },
      {
            "name": "JBL Charge 3 Portable Speaker",
            "sku": "JBL-PARTYBOX-11-46",
            "category": "Wearables & Audio",
            "retailPrice": 2160,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium JBL Charge 3 Portable Speaker",
            "threeDModelUrl": "/assets/models/jbl-partybox-110-speaker.glb"
      },
      {
            "name": "JBL PartyBox 110 Speaker",
            "sku": "JBL-T450-WIRED--47",
            "category": "Wearables & Audio",
            "retailPrice": 16800,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium JBL PartyBox 110 Speaker",
            "threeDModelUrl": "/assets/models/jbl-t450-wired-headphones.glb"
      },
      {
            "name": "JBL T450 Wired Headphones",
            "sku": "JBL-TUNE-720BT--48",
            "category": "Wearables & Audio",
            "retailPrice": 540,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium JBL T450 Wired Headphones",
            "threeDModelUrl": "/assets/models/jbl-tune-720bt-wireless-headphones.glb"
      },
      {
            "name": "JBL Tune 720BT Wireless Headphones",
            "sku": "JBL-TOUR-ONE-M2-49",
            "category": "Wearables & Audio",
            "retailPrice": 2160,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium JBL Tune 720BT Wireless Headphones",
            "threeDModelUrl": "/assets/models/jbl-tour-one-m2-headphones.glb"
      },
      {
            "name": "JBL Tour One M2 Headphones",
            "sku": "JBL-TOUR-PRO-2--50",
            "category": "Wearables & Audio",
            "retailPrice": 6600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium JBL Tour One M2 Headphones",
            "threeDModelUrl": "/assets/models/jbl-tour-pro-2-tws-earbuds.glb"
      },
      {
            "name": "JBL Tour Pro 2 TWS Earbuds",
            "sku": "JBL-RGB-GAMING--51",
            "category": "Wearables & Audio",
            "retailPrice": 5400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium JBL Tour Pro 2 TWS Earbuds",
            "threeDModelUrl": "/assets/models/jbl-rgb-gaming-headphones.glb"
      },
      {
            "name": "JBL RGB Gaming Headphones",
            "sku": "CLINICAL-ANESTH-52",
            "category": "Wearables & Audio",
            "retailPrice": 1440,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium JBL RGB Gaming Headphones",
            "threeDModelUrl": "/assets/models/clinical-anesthesia-workstation.glb"
      },
      {
            "name": "GoPro Hero 11 Black Mini",
            "sku": "ICU-ELECTRIC-HO-53",
            "category": "Wearables & Audio",
            "retailPrice": 25200,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium GoPro Hero 11 Black Mini",
            "threeDModelUrl": "/assets/models/icu-electric-hospital-bed-unit.glb"
      },
      {
            "name": "GoPro Hero 13 Black",
            "sku": "VITACOREX-PATIE-54",
            "category": "Wearables & Audio",
            "retailPrice": 37200,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium GoPro Hero 13 Black",
            "threeDModelUrl": "/assets/models/vitacore-x-patient-monitor.glb"
      },
      {
            "name": "Insta360 ONE X2 Action Camera",
            "sku": "STERILE-MEDICAL-55",
            "category": "Cameras, Power & Action Boards",
            "retailPrice": 31200,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Insta360 ONE X2 Action Camera",
            "threeDModelUrl": "/assets/models/sterile-medical-syringe.glb"
      },
      {
            "name": "50,000mAh Heavy Duty Power Bank",
            "sku": "3PLY-DISPOSABLE-56",
            "category": "Cameras, Power & Action Boards",
            "retailPrice": 1140,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium 50,000mAh Heavy Duty Power Bank",
            "threeDModelUrl": "/assets/models/3-ply-disposable-face-masks-50-pack.glb"
      },
      {
            "name": "Arcadia Wooden Longboard",
            "sku": "ARCADIA-WOODEN--57",
            "category": "Cameras, Power & Action Boards",
            "retailPrice": 1440,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Arcadia Wooden Longboard",
            "threeDModelUrl": "/assets/models/arcadia-wooden-longboard.glb"
      },
      {
            "name": "OneWheel Pint Electric Board",
            "sku": "ONEWHEEL-PINT-E-58",
            "category": "Cameras, Power & Action Boards",
            "retailPrice": 33600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium OneWheel Pint Electric Board",
            "threeDModelUrl": "/assets/models/onewheel-pint-electric-board.glb"
      },
      {
            "name": "Chevrolet Corvette C6.R 1:18 Toy Car",
            "sku": "CHEVROLET-CORVE-59",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 780,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Chevrolet Corvette C6.R 1:18 Toy Car",
            "threeDModelUrl": "/assets/models/chevrolet-corvette-c6-r-1-18-toy-car.glb"
      },
      {
            "name": "McLaren 650S GT3 1:24 Toy Car",
            "sku": "MCLAREN-650S-GT-60",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 504,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium McLaren 650S GT3 1:24 Toy Car",
            "threeDModelUrl": "/assets/models/mclaren-650s-gt3-1-24-toy-car.glb"
      },
      {
            "name": "McLaren 720S GT3 1:18 Toy Car",
            "sku": "MCLAREN-720S-GT-61",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 840,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium McLaren 720S GT3 1:18 Toy Car",
            "threeDModelUrl": "/assets/models/mclaren-720s-gt3-1-18-toy-car.glb"
      },
      {
            "name": "Porsche 992 GT3 R 1:18 Toy Car",
            "sku": "PORSCHE-992-GT3-62",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 900,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Porsche 992 GT3 R 1:18 Toy Car",
            "threeDModelUrl": "/assets/models/porsche-992-gt3-r-1-18-toy-car.glb"
      },
      {
            "name": "BMW M3 GTR GT2 Toy Car",
            "sku": "BMW-M3-GTR-GT2--63",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 384,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium BMW M3 GTR GT2 Toy Car",
            "threeDModelUrl": "/assets/models/bmw-m3-gtr-gt2-toy-car.glb"
      },
      {
            "name": "BMW M6 GT3 Toy Car",
            "sku": "BMW-M6-GT3-TOY--64",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 480,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium BMW M6 GT3 Toy Car",
            "threeDModelUrl": "/assets/models/bmw-m6-gt3-toy-car.glb"
      },
      {
            "name": "1963 Chevrolet C10 Vintage Pickup Toy",
            "sku": "1963-CHEVROLET--65",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 456,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium 1963 Chevrolet C10 Vintage Pickup Toy",
            "threeDModelUrl": "/assets/models/1963-chevrolet-c10-vintage-pickup-toy.glb"
      },
      {
            "name": "MD 500 Military RC Helicopter",
            "sku": "MD-500-MILITARY-66",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 780,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium MD 500 Military RC Helicopter",
            "threeDModelUrl": "/assets/models/md-500-military-rc-helicopter.glb"
      },
      {
            "name": "Neon Chrome Sci-Fi Toy Tank",
            "sku": "NEON-CHROME-SCI-67",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 1080,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Neon Chrome Sci-Fi Toy Tank",
            "threeDModelUrl": "/assets/models/neon-chrome-sci-fi-toy-tank.glb"
      },
      {
            "name": "Transformers Optimus Prime Action Figure",
            "sku": "TRANSFORMERS-OP-68",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 1020,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Transformers Optimus Prime Action Figure",
            "threeDModelUrl": "/assets/models/transformers-optimus-prime-action-figure.glb"
      },
      {
            "name": "Elena of Avalor Princess Crown Toy",
            "sku": "ELENA-OF-AVALOR-69",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 96,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Elena of Avalor Princess Crown Toy",
            "threeDModelUrl": "/assets/models/elena-of-avalor-princess-crown-toy.glb"
      },
      {
            "name": "Pokemon Masters Snapback Cap",
            "sku": "POKEMON-MASTERS-70",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 144,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Pokemon Masters Snapback Cap",
            "threeDModelUrl": "/assets/models/pokemon-masters-snapback-cap.glb"
      },
      {
            "name": "Pokemon Masters Snapback Cap (Black Variant)",
            "sku": "POKEMON-MASTERS-71",
            "category": "Toys, RC & Die-Cast Collectibles",
            "retailPrice": 144,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Pokemon Masters Snapback Cap (Black Variant)",
            "threeDModelUrl": "/assets/models/pokemon-masters-snapback-cap-variant.glb"
      },
      {
            "name": "Nike Air Jordan 1 Sneakers",
            "sku": "MENS-CLASSIC-PO-72",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 1440,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Nike Air Jordan 1 Sneakers",
            "threeDModelUrl": "/assets/models/mens-classic-polo-shirt.glb"
      },
      {
            "name": "Nike Air Zoom Pegasus 36 Shoes",
            "sku": "OVERSIZED-GRAPH-73",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 1200,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Nike Air Zoom Pegasus 36 Shoes",
            "threeDModelUrl": "/assets/models/oversized-graphic-t-shirt-black.glb"
      },
      {
            "name": "Converse All-Star High-Top Sneakers",
            "sku": "OVERSIZED-GRAPH-74",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 780,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Converse All-Star High-Top Sneakers",
            "threeDModelUrl": "/assets/models/oversized-graphic-t-shirt-white.glb"
      },
      {
            "name": "Vans Old Skool Sneakers",
            "sku": "BLACK-FLAME-STR-75",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 720,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vans Old Skool Sneakers",
            "threeDModelUrl": "/assets/models/black-flame-streetwear-hoodie.glb"
      },
      {
            "name": "RTFKT Cyberpunk LED Sneakers",
            "sku": "TWOTONE-VARSITY-76",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 2160,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium RTFKT Cyberpunk LED Sneakers",
            "threeDModelUrl": "/assets/models/two-tone-varsity-hoodie.glb"
      },
      {
            "name": "Women's Classic High Heel Pumps",
            "sku": "TOMMY-HILFIGER--77",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 660,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Women's Classic High Heel Pumps",
            "threeDModelUrl": "/assets/models/tommy-hilfiger-puffer-jacket.glb"
      },
      {
            "name": "Men's Leather Oxford Dress Shoe",
            "sku": "WOMENS-RIBBED-C-78",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 1020,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Men's Leather Oxford Dress Shoe",
            "threeDModelUrl": "/assets/models/womens-ribbed-crop-top-skirt.glb"
      },
      {
            "name": "Men's Classic Polo Shirt",
            "sku": "WOMENS-BELTED-L-79",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 300,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Men's Classic Polo Shirt",
            "threeDModelUrl": "/assets/models/womens-belted-long-overcoat.glb"
      },
      {
            "name": "Oversized Graphic T-Shirt - Black",
            "sku": "VINTAGE-WASHED--80",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 264,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Oversized Graphic T-Shirt - Black",
            "threeDModelUrl": "/assets/models/vintage-washed-dad-hat.glb"
      },
      {
            "name": "Oversized Graphic T-Shirt - White",
            "sku": "VINTAGE-WASHED--81",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 264,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Oversized Graphic T-Shirt - White",
            "threeDModelUrl": "/assets/models/vintage-washed-dad-hat-variant.glb"
      },
      {
            "name": "Black Flame Streetwear Hoodie",
            "sku": "TACTICAL-HALFFI-82",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 660,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Black Flame Streetwear Hoodie",
            "threeDModelUrl": "/assets/models/tactical-half-finger-combat-gloves.glb"
      },
      {
            "name": "Two-Tone Varsity Hoodie",
            "sku": "FRESHWATER-PEAR-83",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 720,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Two-Tone Varsity Hoodie",
            "threeDModelUrl": "/assets/models/freshwater-pearl-necklace.glb"
      },
      {
            "name": "Tommy Hilfiger Puffer Jacket",
            "sku": "SOLITAIRE-GEMST-84",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 1500,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Tommy Hilfiger Puffer Jacket",
            "threeDModelUrl": "/assets/models/solitaire-gemstone-ring.glb"
      },
      {
            "name": "Women's Ribbed Crop Top & Skirt",
            "sku": "RAW-CRYSTAL-PEN-85",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 420,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Women's Ribbed Crop Top & Skirt",
            "threeDModelUrl": "/assets/models/raw-crystal-pendant-necklace.glb"
      },
      {
            "name": "Women's Belted Long Overcoat",
            "sku": "JADE-DONUT-PEND-86",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 1320,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Women's Belted Long Overcoat",
            "threeDModelUrl": "/assets/models/jade-donut-pendant-necklace.glb"
      },
      {
            "name": "Vintage Washed Dad Hat",
            "sku": "JASHIN-SYMBOL-A-87",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 108,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vintage Washed Dad Hat",
            "threeDModelUrl": "/assets/models/jashin-symbol-anime-necklace.glb"
      },
      {
            "name": "Vintage Washed Dad Hat (Navy Variant)",
            "sku": "JASHIN-SYMBOL-A-88",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 108,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vintage Washed Dad Hat (Navy Variant)",
            "threeDModelUrl": "/assets/models/jashin-symbol-anime-necklace-variant.glb"
      },
      {
            "name": "Tactical Half-Finger Combat Gloves",
            "sku": "MINIMALIST-FINE-89",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 180,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Tactical Half-Finger Combat Gloves",
            "threeDModelUrl": "/assets/models/minimalist-fine-cable-chain.glb"
      },
      {
            "name": "Commuter Laptop Backpack",
            "sku": "CURB-CUBAN-LINK-90",
            "category": "Apparel, Shoes & Fashion",
            "retailPrice": 540,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Commuter Laptop Backpack",
            "threeDModelUrl": "/assets/models/curb-cuban-link-chain.glb"
      },
      {
            "name": "Commuter Laptop Backpack (Grey Variant)",
            "sku": "CLASSIC-AVIATOR-91",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 540,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Commuter Laptop Backpack (Grey Variant)",
            "threeDModelUrl": "/assets/models/classic-aviator-sunglasses.glb"
      },
      {
            "name": "Vintage Canvas Trekking Backpack",
            "sku": "BLUE-LIGHT-BLOC-92",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 780,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vintage Canvas Trekking Backpack",
            "threeDModelUrl": "/assets/models/blue-light-blocking-optical-glasses.glb"
      },
      {
            "name": "Tactical Military Duffel Bag",
            "sku": "IPHONE-13-PRO-S-93",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 660,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Tactical Military Duffel Bag",
            "threeDModelUrl": "/assets/models/iphone-13-pro-silicone-case.glb"
      },
      {
            "name": "Minimalist Travel Shoulder Bag",
            "sku": "NIKE-AIR-JORDAN-94",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 336,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Minimalist Travel Shoulder Bag",
            "threeDModelUrl": "/assets/models/nike-air-jordan-1-sneakers.glb"
      },
      {
            "name": "Women's Quilted Leather Handbag",
            "sku": "NIKE-AIR-ZOOM-P-95",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 624,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Women's Quilted Leather Handbag",
            "threeDModelUrl": "/assets/models/nike-air-zoom-pegasus-36-shoes.glb"
      },
      {
            "name": "Freshwater Pearl Necklace",
            "sku": "CONVERSE-ALLSTA-96",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 216,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Freshwater Pearl Necklace",
            "threeDModelUrl": "/assets/models/converse-all-star-high-top-sneakers.glb"
      },
      {
            "name": "Solitaire Gemstone Ring",
            "sku": "VANS-OLD-SKOOL--97",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 72,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Solitaire Gemstone Ring",
            "threeDModelUrl": "/assets/models/vans-old-skool-sneakers.glb"
      },
      {
            "name": "Raw Crystal Pendant Necklace",
            "sku": "RTFKT-CYBERPUNK-98",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 96,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Raw Crystal Pendant Necklace",
            "threeDModelUrl": "/assets/models/rtfkt-cyberpunk-led-sneakers.glb"
      },
      {
            "name": "Jade Donut Pendant Necklace",
            "sku": "WOMENS-CLASSIC--99",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 144,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Jade Donut Pendant Necklace",
            "threeDModelUrl": "/assets/models/womens-classic-high-heel-pumps.glb"
      },
      {
            "name": "Jashin Symbol Anime Necklace",
            "sku": "MENS-LEATHER-OX-100",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 48,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Jashin Symbol Anime Necklace",
            "threeDModelUrl": "/assets/models/mens-leather-oxford-dress-shoe.glb"
      },
      {
            "name": "Jashin Symbol Anime Necklace (Silver Variant)",
            "sku": "COMMUTER-LAPTOP-101",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 48,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Jashin Symbol Anime Necklace (Silver Variant)",
            "threeDModelUrl": "/assets/models/commuter-laptop-backpack.glb"
      },
      {
            "name": "Minimalist Fine Cable Chain",
            "sku": "COMMUTER-LAPTOP-102",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 36,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Minimalist Fine Cable Chain",
            "threeDModelUrl": "/assets/models/commuter-laptop-backpack-variant.glb"
      },
      {
            "name": "Curb Cuban Link Chain",
            "sku": "VINTAGE-CANVAS--103",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 96,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Curb Cuban Link Chain",
            "threeDModelUrl": "/assets/models/vintage-canvas-trekking-backpack.glb"
      },
      {
            "name": "Classic Aviator Sunglasses",
            "sku": "TACTICAL-MILITA-104",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 72,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Classic Aviator Sunglasses",
            "threeDModelUrl": "/assets/models/tactical-military-duffel-bag.glb"
      },
      {
            "name": "Blue Light Blocking Optical Glasses",
            "sku": "MINIMALIST-TRAV-105",
            "category": "Bags, Jewelry & Eyewear",
            "retailPrice": 84,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Blue Light Blocking Optical Glasses",
            "threeDModelUrl": "/assets/models/minimalist-travel-shoulder-bag.glb"
      },
      {
            "name": "Tactical Serrated Combat Knife",
            "sku": "WOMENS-QUILTED--106",
            "category": "Home, Office & Tools",
            "retailPrice": 216,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Tactical Serrated Combat Knife",
            "threeDModelUrl": "/assets/models/womens-quilted-leather-handbag.glb"
      },
      {
            "name": "iPhone 13 Pro Silicone Case",
            "sku": "TACTICAL-SERRAT-107",
            "category": "Home, Office & Tools",
            "retailPrice": 42,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium iPhone 13 Pro Silicone Case",
            "threeDModelUrl": "/assets/models/tactical-serrated-combat-knife.glb"
      },
      {
            "name": "Solid Wood Kung-Fu Tea Table",
            "sku": "SOLID-WOOD-KUNG-108",
            "category": "Home, Office & Tools",
            "retailPrice": 5400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Solid Wood Kung-Fu Tea Table",
            "threeDModelUrl": "/assets/models/solid-wood-kung-fu-tea-table.glb"
      },
      {
            "name": "Modular L-Shaped Sectional Sofa",
            "sku": "MODULAR-LSHAPED-109",
            "category": "Home, Office & Tools",
            "retailPrice": 14400,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Modular L-Shaped Sectional Sofa",
            "threeDModelUrl": "/assets/models/modular-l-shaped-sectional-sofa.glb"
      },
      {
            "name": "Nordic Desk Lamp",
            "sku": "NORDIC-DESK-LAM-110",
            "category": "Home, Office & Tools",
            "retailPrice": 420,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Nordic Desk Lamp",
            "threeDModelUrl": "/assets/models/nordic-desk-lamp.glb"
      },
      {
            "name": "Low-Poly Bedside Table Lamp",
            "sku": "LOWPOLY-BEDSIDE-111",
            "category": "Home, Office & Tools",
            "retailPrice": 336,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Low-Poly Bedside Table Lamp",
            "threeDModelUrl": "/assets/models/low-poly-bedside-table-lamp.glb"
      },
      {
            "name": "Ergonomic Mesh Office Chair",
            "sku": "ERGONOMIC-MESH--112",
            "category": "Home, Office & Tools",
            "retailPrice": 2160,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Ergonomic Mesh Office Chair",
            "threeDModelUrl": "/assets/models/ergonomic-mesh-office-chair.glb"
      },
      {
            "name": "Smart Biometric Digital Door Lock",
            "sku": "GOPRO-HERO-11-B-113",
            "category": "Home, Office & Tools",
            "retailPrice": 2640,
            "status": "PUBLISHED",
            "isTrending": true,
            "stock": 500,
            "description": "Premium Smart Biometric Digital Door Lock",
            "threeDModelUrl": "/assets/models/gopro-hero-11-black-mini.glb"
      },
      {
            "name": "Clinical Anesthesia Workstation",
            "sku": "GOPRO-HERO-13-B-114",
            "category": "Medical & Laboratory",
            "retailPrice": 144000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Clinical Anesthesia Workstation",
            "threeDModelUrl": "/assets/models/gopro-hero-13-black.glb"
      },
      {
            "name": "ICU Electric Hospital Bed Unit",
            "sku": "INSTA360-ONE-X2-115",
            "category": "Medical & Laboratory",
            "retailPrice": 54000,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium ICU Electric Hospital Bed Unit",
            "threeDModelUrl": "/assets/models/insta360-one-x2-action-camera.glb"
      },
      {
            "name": "Vitacore-X Patient Monitor",
            "sku": "50000MAH-HEAVY--116",
            "category": "Medical & Laboratory",
            "retailPrice": 21600,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Vitacore-X Patient Monitor",
            "threeDModelUrl": "/assets/models/50000mah-heavy-duty-power-bank.glb"
      },
      {
            "name": "Sterile Medical Syringe",
            "sku": "AMAZON-ECHO-DOT-117",
            "category": "Medical & Laboratory",
            "retailPrice": 3.6,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Sterile Medical Syringe",
            "threeDModelUrl": "/assets/models/amazon-echo-dot-3rd-gen.glb"
      },
      {
            "name": "3-Ply Disposable Face Masks 50-Pack",
            "sku": "SMART-BIOMETRIC-118",
            "category": "Medical & Laboratory",
            "retailPrice": 54,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium 3-Ply Disposable Face Masks 50-Pack",
            "threeDModelUrl": "/assets/models/smart-biometric-digital-door-lock.glb"
      },
      {
            "name": "Amber Glass Serum Dropper Bottle",
            "sku": "AMBER-GLASS-SER-119",
            "category": "Beauty & Packaging",
            "retailPrice": 9.6,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Amber Glass Serum Dropper Bottle",
            "threeDModelUrl": "/assets/models/amber-glass-serum-dropper-bottle.glb"
      },
      {
            "name": "Matte Cosmetic Squeeze Tube",
            "sku": "MATTE-COSMETIC--120",
            "category": "Beauty & Packaging",
            "retailPrice": 6,
            "status": "PUBLISHED",
            "isTrending": false,
            "stock": 500,
            "description": "Premium Matte Cosmetic Squeeze Tube",
            "threeDModelUrl": "/assets/models/matte-cosmetic-squeeze-tube.glb"
      }
];

    await Product.insertMany(seedData);

    return NextResponse.json({ message: 'Database seeded successfully', count: seedData.length });
  } catch (error) {
    console.error('Seed error:', error); return NextResponse.json({ error: error.message, stack: error.stack }, { status: 500 });
    return NextResponse.json({ error: 'Failed to seed database' }, { status: 500 });
  }
}
